interface SearchBarProps {
    searchQuery: string;
    setSearchQuery: (query: string) => void;
  }
  
  const SearchBar = ({ searchQuery, setSearchQuery }: SearchBarProps) => {
    
    /**
     * onChange:
     * - Triggered when the user types into the search input field.
     * - Updates the `searchQuery` state by calling `setSearchQuery` with the current input value.
     * 
     * @param e - The change event generated by the input field.
     */
    return (
      <input
        type="text"
        placeholder="Search memories..."
        value={searchQuery} 
        onChange={(e) => setSearchQuery(e.target.value)} 
        className="block w-full p-2 border border-gray-300 rounded mb-4"
      />
    );
  };
  
  export default SearchBar;
  