interface SortDropdownProps {
    sortOption: string;
    setSortOption: (option: string) => void;
  }
  
  const SortDropdown = ({ sortOption, setSortOption }: SortDropdownProps) => {
    
    /**
     * onChange:
     * - Triggered when the user selects a different sorting option from the dropdown.
     * - Calls `setSortOption` to update the sorting option based on the selected value.
     * 
     * @param e - The change event generated by the select dropdown.
     */
    
    return (
      <select
        value={sortOption}  
        onChange={(e) => setSortOption(e.target.value)}  
        className="block p-2 border border-gray-300 rounded"
      >
        <option value="newToOld">Newest to Oldest</option>
        <option value="oldToNew">Oldest to Newest</option>
      </select>
    );
  };
  
  export default SortDropdown;
  